<template>
  <div class="clearfix">
    <a-upload
      v-model:file-list="fileList"
      action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
      list-type="picture-card"
      @preview="handlePreview"
    >
      <div v-if="fileList.length < 3">
        <plus-outlined />
        <div style="margin-top: 8px">上传图片</div>
      </div>
    </a-upload>
    <a-modal :visible="previewVisible" :title="previewTitle" :footer="null" @cancel="handleCancel">
      <img alt="example" style="width: 100%" :src="previewImage" />
    </a-modal>
  </div>
</template>
<script lang="ts">
import { PlusOutlined } from '@ant-design/icons-vue';
import { defineComponent, ref } from 'vue';
import type { UploadProps } from 'ant-design-vue';

function getBase64(file: File) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result);
    reader.onerror = error => reject(error);
  });
}

export default defineComponent({
  components: {
    PlusOutlined,
  },
  setup() {
    const previewVisible = ref(false);
    const previewImage = ref('');
    const previewTitle = ref('');

    const fileList = ref<UploadProps['fileList']>([]);

    const handleCancel = () => {
      previewVisible.value = false;
      previewTitle.value = '';
    };
    const handlePreview = async (file: UploadProps['fileList'][number]) => {
      if (!file.url && !file.preview) {
        file.preview = (await getBase64(file.originFileObj)) as string;
      }
      previewImage.value = file.url || file.preview;
      previewVisible.value = true;
      previewTitle.value = file.name || file.url.substring(file.url.lastIndexOf('/') + 1);
    };

    // const classify = {
    //     "推荐": [],
    //     "Python": [
    //         "fastapi",
    //         "scikit-learn",
    //         "pyqt",
    //         "virtualenv",
    //         "pip",
    //         "python",
    //         "pytest",
    //         "pandas",
    //         "flask",
    //         "scrapy",
    //         "web3.py",
    //         "dash",
    //         "pillow",
    //         "jupter",
    //         "httpx",
    //         "scipy",
    //         "gunicorn",
    //         "matplotlib",
    //         "plotly",
    //         "beautifulsoup",
    //         "django",
    //         "ipython",
    //         "pygame",
    //         "tornado",
    //         "numpy",
    //         "conda"
    //     ],
    //     "Java": [
    //         "log4j",
    //         "sentinel",
    //         "servlet",
    //         "java-zookeeper",
    //         "guava",
    //         "intellij-idea",
    //         "junit",
    //         "java-rabbitmq",
    //         "mybatis",
    //         "nio",
    //         "java-activemq",
    //         "maven",
    //         "hibernate",
    //         "java",
    //         "kafka",
    //         "java-ee",
    //         "eclipse",
    //         "jvm",
    //         "tomcat",
    //         "spring",
    //         "struts",
    //         "spring cloud",
    //         "java-consul",
    //         "dubbo",
    //         "java-rocketmq",
    //         "jetty",
    //         "sdkman",
    //         "spring boot"
    //     ],
    //     "编程语言": [
    //         "golang",
    //         "php",
    //         "qt",
    //         "c++",
    //         "lisp",
    //         "swift",
    //         "c语言",
    //         "typescript",
    //         "python",
    //         "c#",
    //         "青少年编程",
    //         "java",
    //         "scala",
    //         "batch",
    //         "ruby",
    //         "matlab",
    //         "perl",
    //         "开发语言",
    //         "objective-c",
    //         "kotlin",
    //         "javascript",
    //         "actionscript",
    //         "rust",
    //         "erlang",
    //         "julia",
    //         "bash",
    //         "r语言",
    //         "lua"
    //     ],
    //     "开发工具": [
    //         "visual studio",
    //         "macos",
    //         "vim",
    //         "pycharm",
    //         "yapi",
    //         "intellij idea",
    //         "git",
    //         "sublime text",
    //         "arcgis",
    //         "emacs",
    //         "docker",
    //         "intellij-idea",
    //         "编辑器",
    //         "phpstorm",
    //         "gitlab",
    //         "visualstudio",
    //         "myeclipse",
    //         "windows",
    //         "vscode",
    //         "github",
    //         "ci",
    //         "jupyter",
    //         "webstorm",
    //         "postman",
    //         "eclipse",
    //         "ide",
    //         "idea",
    //         "svn",
    //         "visual studio code"
    //     ],
    //     "数据结构与算法": [
    //         "逻辑回归",
    //         "剪枝",
    //         "预编码算法",
    //         "迭代加深",
    //         "动态规划",
    //         "深度优先",
    //         "决策树",
    //         "启发式算法",
    //         "图搜索算法",
    //         "散列表",
    //         "支持向量机",
    //         "数据结构",
    //         "爬山算法",
    //         "算法",
    //         "随机森林",
    //         "近邻算法",
    //         "b树",
    //         "线性回归",
    //         "leetcode",
    //         "广度优先",
    //         "宽度优先",
    //         "kmeans",
    //         "贪心算法",
    //         "模拟退火算法",
    //         "链表",
    //         "哈希算法",
    //         "均值算法",
    //         "霍夫曼树",
    //         "最小二乘法",
    //         "排序算法",
    //         "推荐算法"
    //     ],
    //     "大数据": [
    //         "faiss",
    //         "cloudera",
    //         "涛思数据",
    //         "memcache",
    //         "时序数据库",
    //         "etl",
    //         "jina",
    //         "tidb",
    //         "json",
    //         "kafka",
    //         "nosql",
    //         "hadoop",
    //         "rocketmq",
    //         "elasticsearch",
    //         "sqlserver",
    //         "大数据",
    //         "ambari",
    //         "big data",
    //         "activemq",
    //         "iotdb",
    //         "powerbi",
    //         "tdengine",
    //         "mapreduce",
    //         "postgresql",
    //         "sequoiadb",
    //         "oracle",
    //         "sql",
    //         "odps",
    //         "memcached",
    //         "mongodb",
    //         "mysql",
    //         "storm",
    //         "milvus",
    //         "neo4j",
    //         "consul",
    //         "finebi",
    //         "couchdb",
    //         "rabbitmq",
    //         "talkingdata",
    //         "mariadb",
    //         "hdfs",
    //         "hbase",
    //         "ceph",
    //         "clickhouse",
    //         "sqlite",
    //         "eureka",
    //         "graphsql",
    //         "数据库",
    //         "sqoop",
    //         "数据仓库",
    //         "redis",
    //         "opentsdb",
    //         "zookeeper",
    //         "spark",
    //         "etcd",
    //         "oceanbase",
    //         "flume",
    //         "flink",
    //         "tdenging",
    //         "database",
    //         "kylin",
    //         "hive"
    //     ],
    //     "数据库管理": [
    //         "数据库架构",
    //         "etl工程师",
    //         "dba",
    //         "数据仓库",
    //         "数据库开发"
    //     ],
    //     "前端": [
    //         "前端框架",
    //         "npm",
    //         "tdesign",
    //         "scss",
    //         "javascript",
    //         "css3",
    //         "electron",
    //         "easyui",
    //         "html5",
    //         "ajax",
    //         "reactjs",
    //         "正则表达式",
    //         "express",
    //         "postman",
    //         "json",
    //         "acrodesign",
    //         "bootstrap",
    //         "angular.js",
    //         "firebug",
    //         "html",
    //         "gulp",
    //         "前端",
    //         "webpack",
    //         "firefox",
    //         "jquery",
    //         "postcss",
    //         "elementui",
    //         "stylus",
    //         "view design",
    //         "es6",
    //         "typescript",
    //         "less",
    //         "angular",
    //         "edge",
    //         "webkit",
    //         "sass",
    //         "csrf",
    //         "vue.js",
    //         "safari",
    //         "echarts",
    //         "coffeescript",
    //         "ecmascript",
    //         "chrome devtools",
    //         "elementui",
    //         "css",
    //         "fiddler",
    //         "xss",
    //         "chrome",
    //         "anti-design-vue",
    //         "yarn",
    //         "layui",
    //         "react.js",
    //         "xhtml",
    //         "node.js"
    //     ],
    //     "后端": [
    //         "spring boot",
    //         "spring cloud",
    //         "swoole",
    //         "后端",
    //         "ribbon",
    //         "sentinel",
    //         "sql",
    //         "nginx",
    //         "golang",
    //         "lavarel",
    //         "asp.net",
    //         "spring",
    //         "架构",
    //         "scala",
    //         "rust",
    //         "graphql",
    //         "tomcat",
    //         "分布式",
    //         "ruby",
    //         "restful",
    //         "django",
    //         "mysql",
    //         "logback",
    //         "ruby on rails",
    //         "rabbitmq",
    //         "beego",
    //         "爬虫",
    //         "flask",
    //         "中间件",
    //         "gateway",
    //         "php",
    //         "hystrix",
    //         "gin",
    //         "node.js"
    //     ],
    //     "云原生": [
    //         "eureka",
    //         "服务发现",
    //         "serverless",
    //         "docker",
    //         "rancher",
    //         "容器",
    //         "微服务",
    //         "openshift",
    //         "kubeless",
    //         "devops",
    //         "openstack",
    //         "kubernetes",
    //         "kind",
    //         "paas",
    //         "argocd",
    //         "etcd",
    //         "harvester",
    //         "jenkins",
    //         "云原生",
    //         "zookeeper",
    //         "consul",
    //         "knative",
    //         "kubelet",
    //         "service_mesh",
    //         "istio",
    //         "terraform",
    //         "gateway"
    //     ],
    //     "移动开发": [
    //         "android",
    //         "android studio",
    //         "objective-c",
    //         "xcode",
    //         "flutter",
    //         "ios",
    //         "kotlin",
    //         "swift",
    //         "xamarin",
    //         "web app",
    //         "小程序",
    //         "reactnative",
    //         "react native"
    //     ],
    //     "Android": [
    //         "retrofit",
    //         "xml",
    //         "zygote",
    //         "glide",
    //         "apache",
    //         "gradle",
    //         "binder",
    //         "rxjava",
    //         "adb",
    //         "android-studio",
    //         "dalvik",
    //         "android jetpack",
    //         "appcompat",
    //         "webview",
    //         "android runtime",
    //         "okhttp",
    //         "android",
    //         "androidx"
    //     ],
    //     "iOS": [
    //         "macos",
    //         "ipad",
    //         "swiftui",
    //         "cocoapods",
    //         "cocoa",
    //         "iphone",
    //         "wwdc",
    //         "safari",
    //         "objective-c",
    //         "rxswift",
    //         "phonegap",
    //         "ios",
    //         "xcode",
    //         "swift"
    //     ],
    //     "人工智能": [
    //         "边缘计算",
    //         "人工智能",
    //         "tensorflow",
    //         "超分辨率重建",
    //         "语言模型",
    //         "lstm",
    //         "keras",
    //         "聚类",
    //         "神经网络",
    //         "目标检测",
    //         "gpt-3",
    //         "图像处理",
    //         "xlnet",
    //         "智慧城市",
    //         "数据挖掘",
    //         "paddlepaddle",
    //         "深度学习",
    //         "spark-ml",
    //         "mxnet",
    //         "目标跟踪",
    //         "openvino",
    //         "自动驾驶",
    //         "数据分析",
    //         "知识图谱",
    //         "视觉检测",
    //         "word2vec",
    //         "迁移学习",
    //         "rnn",
    //         "opencv",
    //         "计算机视觉",
    //         "dnn",
    //         "机器翻译",
    //         "scikit-learn",
    //         "pytorch",
    //         "bert",
    //         "gru",
    //         "分类",
    //         "自然语言处理",
    //         "生成对抗网络",
    //         "transformer",
    //         "boosting",
    //         "mnn",
    //         "语音识别",
    //         "mllib",
    //         "oneflow",
    //         "nlp",
    //         "机器学习",
    //         "mlnet",
    //         "回归",
    //         "集成学习",
    //         "caffe",
    //         "sklearn",
    //         "cnn"
    //     ],
    //     "网络": [
    //         "https",
    //         "p2p",
    //         "ssl",
    //         "5G",
    //         "rpc",
    //         "websocket",
    //         "udp",
    //         "网络协议",
    //         "wireshark",
    //         "tcpdump",
    //         "http",
    //         "tcp/ip",
    //         "网络安全"
    //     ],
    //     "嵌入式": [
    //         "proteus",
    //         "arm",
    //         "嵌入式硬件",
    //         "嵌入式实时数据库",
    //         "iot",
    //         "51单片机",
    //         "rtdbs",
    //         "单片机",
    //         "物联网",
    //         "mcu",
    //         "stm32"
    //     ],
    //     "硬件开发": [
    //         "硬件架构",
    //         "精益工程",
    //         "pcb工艺",
    //         "dsp开发",
    //         "基带工程",
    //         "驱动开发",
    //         "射频工程",
    //         "arm开发",
    //         "材料工程",
    //         "硬件工程",
    //         "fpga开发"
    //     ],
    //     "PHP": [
    //         "composer",
    //         "symfony",
    //         "php",
    //         "laravel",
    //         "nginx",
    //         "apache",
    //         "mvc"
    //     ],
    //     "游戏": [
    //         "cryengine",
    //         "unity",
    //         "骨骼绑定",
    //         "着色器",
    //         "houdini",
    //         "数字雕刻",
    //         "topogun",
    //         "mr",
    //         "lumberyard",
    //         "cinema4d",
    //         "材质",
    //         "ogre",
    //         "rizomuv",
    //         "substance designer",
    //         "pygame",
    //         "3dsmax",
    //         "游戏美术",
    //         "blender",
    //         "vr",
    //         "技术美术",
    //         "xr",
    //         "zbrush",
    //         "cocos2d",
    //         "uv",
    //         "游戏引擎",
    //         "游戏策划",
    //         "maya",
    //         "关卡设计",
    //         "godot",
    //         "3dcoat",
    //         "quixel",
    //         "图形渲染",
    //         "重拓扑",
    //         "ar",
    //         "动画",
    //         "ue4",
    //         "贴图",
    //         "spine",
    //         "虚幻",
    //         "游戏程序",
    //         "cascadeur",
    //         "ue5",
    //         "substance painter"
    //     ],
    //     "开放平台": [
    //         "微信",
    //         "oneapi",
    //         "微信公众平台",
    //         "百度",
    //         "新浪微博",
    //         "facebook",
    //         "paddle",
    //         "twitter",
    //         "微信开放平台"
    //     ],
    //     "HarmonyOS": [
    //         "华为云",
    //         "华为",
    //         "harmonyos"
    //     ],
    //     "微软技术": [
    //         "azure",
    //         "linq",
    //         "mssql",
    //         "windows",
    //         ".net",
    //         "microsoft",
    //         "visual studio",
    //         "mfc",
    //         "c#",
    //         "sqlserver",
    //         "sql",
    //         "sharepoint",
    //         "wpf",
    //         "asp.net",
    //         ".netcore",
    //         "xamarin",
    //         "hololens",
    //         "typescript"
    //     ],
    //     "扩展屏应用开发": [
    //         "TV",
    //         "大屏端",
    //         "智能电视",
    //         "扩展屏应用开发"
    //     ],
    //     "小程序": [
    //         "taro",
    //         "百度小程序",
    //         "小程序",
    //         "uni-app",
    //         "微信小程序"
    //     ],
    //     "操作系统": [
    //         "blackberry",
    //         "macos",
    //         "centos",
    //         "harmonyos",
    //         "risc-v",
    //         "ubuntu",
    //         "linux",
    //         "windows",
    //         "gnu"
    //     ],
    //     "搜索": [
    //         "solr",
    //         "全文检索",
    //         "搜索引擎",
    //         "sphinx",
    //         "lucene",
    //         "elasticsearch",
    //         "中文分词"
    //     ],
    //     "设计模式": [
    //         "备忘录模式",
    //         "适配器模式",
    //         "责任链模式",
    //         "建造者模式",
    //         "设计模式",
    //         "迪米特法则",
    //         "模板方法模式",
    //         "命令模式",
    //         "策略模式",
    //         "接口隔离原则",
    //         "访问者模式",
    //         "开闭原则",
    //         "工厂方法模式",
    //         "装饰器模式",
    //         "单例模式",
    //         "中介者模式",
    //         "享元模式",
    //         "单一职责原则",
    //         "桥接模式",
    //         "合成复用原则",
    //         "依赖倒置原则",
    //         "代理模式",
    //         "uml",
    //         "组合模式",
    //         "解释器模式",
    //         "原型模式",
    //         "里氏替换原则",
    //         "简单工厂模式",
    //         "状态模式",
    //         "迭代器模式",
    //         "外观模式",
    //         "观察者模式",
    //         "抽象工厂模式"
    //     ],
    //     "测试": [
    //         "安全性测试",
    //         "集成测试",
    //         "ab测试",
    //         "威胁分析",
    //         "模块测试",
    //         "metersphere",
    //         "测试覆盖率",
    //         "压力测试",
    //         "测试工具",
    //         "单元测试",
    //         "jira",
    //         "testlink",
    //         "selenium",
    //         "postman",
    //         "功能测试",
    //         "jmeter",
    //         "可用性测试",
    //         "appuim",
    //         "测试用例"
    //     ],
    //     "云平台": [
    //         "京东云",
    //         "七牛云存储",
    //         "aws",
    //         "火山引擎",
    //         "百度云",
    //         "华为云",
    //         "云计算",
    //         "azure",
    //         "腾讯云",
    //         "CSDN开发云",
    //         "阿里云"
    //     ],
    //     "软件工程": [
    //         "sprint",
    //         "流程图",
    //         "tfs",
    //         "极限编程",
    //         "scrum",
    //         "代码规范",
    //         "设计模式",
    //         "团队开发",
    //         "甘特图",
    //         "tdd",
    //         "ux",
    //         "代码覆盖率",
    //         "敏捷流程",
    //         "设计规范",
    //         "cmmi",
    //         "需求分析",
    //         "redmine",
    //         "源代码管理",
    //         "结对编程",
    //         "ci",
    //         "软件构建",
    //         "bug",
    //         "个人开发",
    //         "jira",
    //         "teambition",
    //         "ui",
    //         "交互",
    //         "性能优化",
    //         "重构",
    //         "软件工程",
    //         "规格说明书",
    //         "issue",
    //         "代码复审"
    //     ],
    //     "区块链": [
    //         "比特币",
    //         "共识算法",
    //         "去中心化",
    //         "零知识证明",
    //         "同态加密",
    //         "以太坊",
    //         "虚拟货币",
    //         "智能合约",
    //         "信任链",
    //         "区块链",
    //         "分布式账本",
    //         "libra",
    //         "数字货币"
    //     ],
    //     "数学": [
    //         "概率论",
    //         "傅立叶分析",
    //         "图论",
    //         "拓扑学",
    //         "抽象代数",
    //         "几何学",
    //         "动态规划",
    //         "矩阵",
    //         "线性代数"
    //     ],
    //     "运维": [
    //         "debian",
    //         "puppet",
    //         "自动化",
    //         "elk",
    //         "ansible",
    //         "负载均衡",
    //         "kubernetes",
    //         "fabric",
    //         "skywalking",
    //         "网络",
    //         "gitea",
    //         "kong",
    //         "grafana",
    //         "sentry",
    //         "服务器",
    //         "apache",
    //         "saltstack",
    //         "lvs",
    //         "运维",
    //         "nginx",
    //         "openresty",
    //         "tekton",
    //         "ezone",
    //         "centos",
    //         "运维开发",
    //         "devops",
    //         "vagrant",
    //         "jenkins",
    //         "zabbix",
    //         "prometheus",
    //         "docker",
    //         "ubuntu",
    //         "ssh",
    //         "graylog",
    //         "linux",
    //         "系统架构",
    //         "容器"
    //     ],
    //     "安全": [
    //         "系统安全",
    //         "安全架构",
    //         "web安全",
    //         "安全"
    //     ],
    //     "服务器": [
    //         "linux",
    //         "ubuntu",
    //         "unix",
    //         "centos",
    //         "负载均衡",
    //         "缓存"
    //     ],
    //     "职场和发展": [
    //         "pat考试",
    //         "leetcode",
    //         "职场和发展",
    //         "蓝桥杯",
    //         "面试",
    //         "程序人生",
    //         "业界资讯"
    //     ],
    //     "教育培训": [
    //         "c5全栈",
    //         "c4前端",
    //         "c5交付",
    //         "c4python",
    //         "c4java",
    //         "c1认证",
    //         "c5底层"
    //     ],
    //     "产品/运营": [
    //         "产品运营",
    //         "新媒体运营",
    //         "用户运营",
    //         "墨刀",
    //         "内容运营",
    //         "流量运营",
    //         "axure"
    //     ],
    //     "设计": [
    //         "3d",
    //         "ux",
    //         "photoshop",
    //         "ui",
    //         "sketch",
    //         "平面",
    //         "交互",
    //         "illustrator"
    //     ],
    //     "其他": [
    //         "经验分享",
    //         "segmentfault",
    //         "其他",
    //         "音视频"
    //     ],
    //     "音视频": [
    //         "音视频",
    //         "语音识别",
    //         "实时互动",
    //         "webrtc",
    //         "计算机视觉",
    //         "视觉检测",
    //         "视频编解码",
    //         "opencv",
    //         "实时音视频"
    //     ],
    //     "行业数字化": [
    //         "游戏",
    //         "健康医疗",
    //         "娱乐",
    //         "零售",
    //         "社交电子",
    //         "旅游",
    //         "媒体",
    //         "交通物流",
    //         "制造",
    //         "能源",
    //         "传媒",
    //         "政务",
    //         "金融",
    //         "教育电商"
    //     ],
    //     "非IT技术": [
    //         "美女",
    //         "玩游戏",
    //         "节日",
    //         "科技",
    //         "美食",
    //         "汽车",
    //         "宠物",
    //         "帅哥",
    //         "求职招聘",
    //         "生活",
    //         "风景",
    //         "交友",
    //         "程序人生",
    //         "学习",
    //         "金融"
    //     ],
    //     "开源": [
    //         "github",
    //         "git",
    //         "开源协议",
    //         "开源软件",
    //         "开源"
    //     ],
    //     "前沿技术": [
    //         "5G",
    //         "低代码",
    //         "ar",
    //         "车载系统",
    //         "web3",
    //         "智能家居",
    //         "无人机",
    //         "vr",
    //         "rpa",
    //         "neo4j",
    //         "量子计算",
    //         "智能硬件",
    //         "机器人",
    //         "wasm",
    //         "fpga开发"
    //     ]
    // }
    //
    // const labelList = [];
    // for (let item in classify) {
    //   const tem = {
    //     label: item,
    //     value: item,
    //     children: []
    //   }
    //   for (let it of classify[item as keyof typeof classify]) {
    //     tem.children.push({
    //       // @ts-ignore
    //       label: it,
    //       // @ts-ignore
    //       value: it,
    //     })
    //   }
    //   labelList.push(tem)
    // }
    return {
      previewVisible,
      previewImage,
      fileList,
      handleCancel,
      handlePreview,
      previewTitle,
    };
  },
});
</script>
<style>
/* you can make up upload button and sample style by using stylesheets */
.ant-upload-select-picture-card i {
  font-size: 32px;
  color: #999;
}

.ant-upload-select-picture-card .ant-upload-text {
  margin-top: 8px;
  color: #666;
}
</style>
